### ISSUE TITLE
Thanks for Windows 98 UTM

### ISSUE THREAD

**Issue by gingerbeardman** [anonymousaga/UTM#2]
I had a hard time setting it up, so gave up and found your image.

My goal is to get my own qcow2 of Windows 98 Japanese working.

https://archive.org/details/windows-98-se-japanese-vmware

A straight qcow2 swap doesn't work so well as my image is missing drivers, I guess. As my image requires me to login with "password" and the keyboard is not recognised I'm at a loss.

Any guidance appreciated!

**Comment by anonymousaga** [comment]
have you ticked on PS2 keyboard already?

**Comment by gingerbeardman** [comment]
Within Windows or in UTM? Consider me a noob with UTM, because I am.

I'm on an M1 Mac so I can't get into the Windows VM to make any changes. Catch 22.

So I might have to reinstall everything from scratch.

**Comment by anonymousaga** [comment]
Utm. And im also on m1 as well.

**Comment by gingerbeardman** [comment]
OK, yes, I took your Windows 98 UTM so all your settings persist, but swapped out the qcow2 file for my own.

![Screen shot 2024-04-17 at 13 16 15](https://github.com/anonymousaga/UTM/assets/49612/2741b350-d255-411c-9839-016945c08b8d)

**Comment by anonymousaga** [comment]
Oh ok, does it work now?

**Comment by gingerbeardman** [comment]
No.

But just so we're clear PS/2 was already set, so I've made no changes, and it's still not working.

If you want to try yourself the VMware image is at the link in the OP.

**Comment by gingerbeardman** [comment]
Is there anything I can do to better explain my situation and receive more help?

**Comment by anonymousaga** [comment]
Sorry, im busy with preparation for my AP exams. I can get back to you sometime later when I have a bit more time.

**Comment by gingerbeardman** [comment]
Sure thing! Thank you and good luck to you

**Comment by anonymousaga** [comment]
Ill get to you in a few days. Sorry for the wait. My exams went well :)

**Comment by gingerbeardman** [comment]
Congrats! 

Strangely I booted up UTM today and then checked GitHub to see this reply. :)

**Comment by anonymousaga** [comment]
I'm not even able to convert the disk to a qcow2 - qemu-img keeps throwing errors.
If you have a bootable qcow2 disk, can you send me that?
Otherwise, I updated my win98 VM utm file. Delete the existing disk, make a new disk, and install using https://archive.org/details/Win98SEJPNRetail

**Comment by anonymousaga** [comment]
Did you end up solving the issue?

**Comment by gingerbeardman** [comment]
Sadly I haven't had the time to try again. But I have needed it!

I've struggled on with an XP VM.

**Comment by anonymousaga** [comment]
I have a utm winxp vm too!

I'll post it this weekend, after I uninstall the software I put on there and remove personal details.

**Comment by gingerbeardman** [comment]
Just so we're talking about the same thing, you mean you'll post the Win 98 VM? If so, awesome! Thanks

**Comment by anonymousaga** [comment]
I mean to say that i can publish a windows XP vm.

I already have a win98 vm posted, and I am unable to convert your VMDK into a qcow2 file for some reason

**Comment by gingerbeardman** [comment]
OK, I will try again soon.

It's Japanese 98 VM that I need.

My XP VM is also Japanese.

I use a lot of old Japanese software and games.

**Comment by anonymousaga** [comment]
I tried to make a win98 vm with [this iso](https://archive.org/details/Win98SEJPNRetail) from scratch

i got stuck at booting the hard disk saying “invalid system disk”

Im sorry that I couldnt help you

**Comment by gingerbeardman** [comment]
No worries, I'll chime back in if I manage it at some point in the future.

**Comment by gingerbeardman** [comment]
I ended up going with Windows XP Japanese and cutting my losses, it installed easily using the standard UTM gallery XP item :)

Cheers!
